### ISSUE TITLE
What is the difference with JDBC API and JAVA API.

### ISSUE THREAD

**Issue by ruanwenjun** [dolphindb/jdbc#2]
I find the JAVA API is more powerful, I can use JAVA API to query the metadata of DATABASE.

Can I use JDBC API to do this? like `show databases()` in mysql.

**Comment by peeyee** [comment]
You can use the following codes to retrieve the schema infomation of a Database:

```java
Statement stmt = conn.createStatement();
ResultSet rs = stmt.executeQuery(String.format("schema(loadTable(%s, %s)).colDefs", "\"dfs://db1\"", "\"t1\""));
```
